### ISSUE TITLE
Named ports not working in Levant

### ISSUE THREAD

**Issue by brettplarson** [hashicorp/levant#448]
**Description**
Cannot plan or deploy jobs using levant that otherwise work when I render them and use the nomad CLI.

I have a go template which renders ports from a yaml file however I get the following error when trying to use levant deploy / plan.
```
[ERROR] levant/command: error parsing 'job': group: network, ports -> Port label does not conform to naming requirements ^[a-zA-Z0-9_]+$
```

Rendering the output and then planning / running works fine, it's something with levant itself that is causing this issue.

even though it seems like levant is no longer maintained, I figure it wouldn't hurt to post this.

**Relevant Nomad job specification file**
YAML:
```yaml

job:
  job_name: comejob
  region: nonprod
  periodic:
    cron: 0 06 * * MON-FRI *
  type: batch
  datacenters:
  - DC1
  constraint:
    host: somehost
  group:
    restart:
      attempts: 0
    reschedule:
      attempts: 0
      unlimited: false
    network:
      ports:
      - name: server
        static: 39399
        to: 9999
      - name: server-pub
        static: 39398
        to: 9998
```

Template:
```yaml
    port [[ .name | quote ]] {
      [[if .to ]] to  = [[ .to ]] [[ end ]]
      [[if .static ]] static = [[ .static ]] [[ end ]]
      }
    [[- end ]]
```

What the port section looks like rendered:
```
      port "server" {
        to     = 9999
        static = 39399
      }
      port "server-pub" {
        to     = 9998
        static = 39398
      }
```

**Output of `levant version`:**

```
Levant v0.3.1
```

**Output of `consul version`:**

```
n/a
```

**Output of `nomad version`:**

```
Nomad v1.2.6 (a6c6b475db5073e33885377b4a5c733e1161020c)
```

**Additional environment details:**

n/a 

**Debug log outputs from Levant:**

```
[ERROR] levant/command: error parsing 'job': group: network, ports -> Port label does not conform to naming requirements ^[a-zA-Z0-9_]+$
```
